[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"

[service]
port = 8080

[variables]
BACKEND_URL = "https://backend-production-ed8f.up.railway.app"
